# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('apellido1', models.CharField(max_length=200)),
                ('apellido2', models.CharField(max_length=200)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('A', 'Asignado'), ('S', 'Suplente'), ('R', 'Renuncia'), ('E', 'Excluido')], max_length=1)),
                ('titulacion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('centro_asignado', models.ForeignKey(default='Sin centro asignado', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Centro')),
            ],
        ),
    ]
