# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='horario_asignado',
            field=models.CharField(choices=[('M', 'Manyana'), ('T', 'Tarde')], default='Sin horario asignado', max_length=1),
        ),
    ]
