# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_horario_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='horario_asignado',
            field=models.CharField(choices=[('M', 'Manyana'), ('T', 'Tarde'), ('N', 'No asignado')], default='N', max_length=1),
        ),
    ]
