# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161021_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
