# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161021_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
