# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161021_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[users.models.dni_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.PositiveIntegerField(validators=[users.models.telefono_validator]),
        ),
    ]
