# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161021_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='centro_asignado',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Centro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[users.models.dni_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(choices=[('A', 'Asignado'), ('S', 'Suplente'), ('R', 'Renuncia'), ('E', 'Excluido'), ('N', 'No asignado')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='horario_asignado',
            field=models.CharField(choices=[('M', 'Ma\xf1ana'), ('T', 'Tarde'), ('N', 'No asignado')], default='N', max_length=1),
        ),
    ]
