# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161021_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='centro_asignado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Centro'),
        ),
    ]
