# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20161025_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='centro_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Centro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^(?i)([a-z\xf1\xe1\xe9\xed\xf3\xfa]{2,60})$')]),
        ),
    ]
